### ISSUE TITLE
Issue in creating rspec test for model

### ISSUE THREAD

**Issue by sachinsaxena1996** [Nedomas/zapata#19]
Hi,

I am running following command in my app root:  zapata generate app/models/user.rb --single

But it gives below error: Please suggest how i can resolve this error:

/gems/zapata-0.1.6/lib/zapata/predictor/args.rb:36:in `choose_values': Not yet implemented (RuntimeError)
        from /usr/local/rvm/gems/ruby-2.2.2@/gems/zapata-0.1.6/lib/zapata/predictor/args.rb:9:in`literal'
        from /usr/local/rvm/gems/ruby-2.2.2@/gems/zapata-0.1.6/lib/zapata/primitive/const_send.rb:15:in `to_raw'
        from /usr/local/rvm/gems/ruby-2.2.2@/gems/zapata-0.1.6/lib/zapata/primitive/send.rb:33:in`to_raw'
        from /usr/local/rvm/gems/ruby-2.2.2@/gems/zapata-0.1.6/lib/zapata/primitive/var.rb:15:in `to_raw'
        from /usr/local/rvm/gems/ruby-2.2.2@nusdigital/gems/zapata-0.1.6/lib/zapata/primitive/arg.rb:11:in`to_raw'
        from /usr/local/rvm/gems/ruby-2.2.2@/gems/zapata-0.1.6/lib/zapata/primitive/array.rb:17:in `block in to_raw'
        from /usr/local/rvm/gems/ruby-2.2.2@/gems/zapata-0.1.6/lib/zapata/primitive/array.rb:15:in`map'
        from /usr/local/rvm/gems/ruby-2.2.2@/gems/zapata-0.1.6/lib/zapata/primitive/array.rb:15:in `to_raw'
        from /usr/local/rvm/gems/ruby-2.2.2@/gems/zapata-0.1.6/lib/zapata/predictor/args.rb:8:in`literal'
        from /usr/local/rvm/gems/ruby-2.2.2@/gems/zapata-0.1.6/lib/zapata/primitive/defs.rb:28:in `literal_predicted_args'
        from /usr/local/rvm/gems/ruby-2.2.2@/gems/zapata-0.1.6/lib/zapata/rzpec/writer.rb:100:in`write_method'
        from /usr/local/rvm/gems/ruby-2.2.2@/gems/zapata-0.1.6/lib/zapata/rzpec/writer.rb:55:in `block in write_class'
        from /usr/local/rvm/gems/ruby-2.2.2@/gems/zapata-0.1.6/lib/zapata/rzpec/writer.rb:54:in`each'
        from /usr/local/rvm/gems/ruby-2.2.2@/gems/zapata-0.1.6/lib/zapata/rzpec/writer.rb:54:in `write_class'
        from /usr/local/rvm/gems/ruby-2.2.2@/gems/zapata-0.1.6/lib/zapata/rzpec/writer.rb:23:in`block in initialize'
        from /usr/local/rvm/gems/ruby-2.2.2@/gems/zapata-0.1.6/lib/zapata/rzpec/writer.rb:22:in `each'
        from /usr/local/rvm/gems/ruby-2.2.2@/gems/zapata-0.1.6/lib/zapata/rzpec/writer.rb:22:in`initialize'
        from /usr/local/rvm/gems/ruby-2.2.2@/gems/zapata-0.1.6/lib/zapata.rb:84:in `new'
        from /usr/local/rvm/gems/ruby-2.2.2@/gems/zapata-0.1.6/lib/zapata.rb:84:in`generate_rspec_for'
        from /usr/local/rvm/gems/ruby-2.2.2@/gems/zapata-0.1.6/lib/zapata.rb:36:in `generate'
        from /usr/local/rvm/gems/ruby-2.2.2@/gems/zapata-0.1.6/lib/zapata.rb:28:in`generate_with_friendly_output'
        from /usr/local/rvm/gems/ruby-2.2.2@/gems/zapata-0.1.6/bin/zapata:20:in `block (3 levels) in <top (required)>'
        from /usr/local/rvm/gems/ruby-2.2.2@/gems/slop-3.6.0/lib/slop.rb:260:in`call'
        from /usr/local/rvm/gems/ruby-2.2.2@/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
        from /usr/local/rvm/gems/ruby-2.2.2@/gems/slop-3.6.0/lib/slop.rb:235:in`parse!'
        from /usr/local/rvm/gems/ruby-2.2.2@/gems/slop-3.6.0/lib/slop.rb:211:in `parse'
        from /usr/local/rvm/gems/ruby-2.2.2@/gems/zapata-0.1.6/bin/zapata:32:in`<top (required)>'
        from /usr/local/rvm/gems/ruby-2.2.2@/bin/zapata:23:in `load'
        from /usr/local/rvm/gems/ruby-2.2.2@/bin/zapata:23:in`<main>'
        from /usr/local/rvm/gems/ruby-2.2.2@/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.2.2@/bin/ruby_executable_hooks:15:in`<main>'

**Comment by Nedomas** [comment]
Hey, is your app in GitHub? I'd check it out myself :)

**Comment by Nedomas** [comment]
Should be fixed with v1.0.0. Thanks to @marcinruszkiewicz #23 and @jpalumickas
