### ISSUE TITLE
Backport to older versions of ruby/rails

### ISSUE THREAD

**Issue by mockdeep** [Nedomas/zapata#2]
I was thinking of building something like this myself, as I'm working on a [legacy project](https://github.com/mockdeep/better) that started with no tests whatsoever. This seems like the sort of tool that would be especially valuable in those cases, so it would be nice for it to work on older versions of ruby and rails so they can be brought up to speed faster.

**Comment by Nedomas** [comment]
Not relevant anymore to most people. You can learn how to hardcode it from this commit: https://github.com/Nedomas/zapata/commit/a570f2c6398ec0ac08dfc142731a0e46fbdcb79c
