### ISSUE TITLE
How to run in ruby 2.4, 2.5 and rails 4 or 5

### ISSUE THREAD

**Issue by kul1** [Nedomas/zapata#21]
ruby 2.1, 2.2, 2.3 
rails 3
No longer support and some gems not work.
Thanks it is very interesting project. Hope I can use it.

**Comment by maniator** [comment]
https://github.com/Nedomas/zapata/pull/23

**Comment by Nedomas** [comment]
Hi @kul1 , @maniator - closing this as the new v1.0.0 was released thanks to @marcinruszkiewicz #23 and @jpalumickas
