### ISSUE TITLE
Did this gem ever work?  Does it just need fixing?

### ISSUE THREAD

**Issue by KelseyDH** [Nedomas/zapata#22]
Very cool idea for a gem, though it appears to be breaking.  Did the author of this library ever get it to work, or was it always breaking?  Wondering if it would be worth trying to fix.

**Comment by Nedomas** [comment]
Hi @KelseyDH - it's an old project but it was working as described around Ruby ~2.1 times. I'm not actively coding with Ruby anymore so can't say for sure what could have changed over the last few versions. 

It might need to have the dependencies updated and breaking changes fixed to make it work today.

**Comment by maniator** [comment]
This PR _may_ fix it up 
https://github.com/Nedomas/zapata/pull/23

**Comment by Nedomas** [comment]
Thanks for the followups - the version 1.0.0 was just released thanks to @marcinruszkiewicz  https://github.com/Nedomas/zapata/pull/23 and @jpalumickas. It now works with the current Ruby 2.6+
