### ISSUE TITLE
`helper_name': Was not able to load nor rails_helper, nor spec_helper

### ISSUE THREAD

**Issue by thejourneydude** [Nedomas/zapata#8]
Running Rails 4.2 and Zapata 0.1.5 renders this error when trying to create a test.

    jason@j:~/ror/test_app$ zapata generate app/models/avatar.rb
    warning: parser/current is loading parser/ruby21, which recognizes
    warning: 2.1.5-compliant syntax, but you are running 2.1.2.
      /home/jason/.rvm/gems/ruby-2.1.2/gems/zapata-0.1.5/lib/zapata/core/loader.rb:23:in `helper_name': Was not able to load nor rails_helper, nor spec_helper (RuntimeError)
      from /home/jason/.rvm/gems/ruby-2.1.2/gems/zapata-0.1.5/lib/zapata/core/loader.rb:38:in `load_spec_helper'
      from /home/jason/.rvm/gems/ruby-2.1.2/gems/zapata-0.1.5/lib/zapata.rb:55:in `initialize'
    from /home/jason/.rvm/gems/ruby-2.1.2/gems/zapata-0.1.5/lib/zapata.rb:36:in `new'
      from /home/jason/.rvm/gems/ruby-2.1.2/gems/zapata-0.1.5/lib/zapata.rb:36:in `generate'
      from /home/jason/.rvm/gems/ruby-2.1.2/gems/zapata-0.1.5/lib/zapata.rb:28:in `generate_with_friendly_output'
    from /home/jason/.rvm/gems/ruby-2.1.2/gems/zapata-0.1.5/bin/zapata:20:in `block (3 levels) in <top (required)>'
      from /home/jason/.rvm/gems/ruby-2.1.2/gems/slop-3.6.0/lib/slop.rb:260:in `call'
      from /home/jason/.rvm/gems/ruby-2.1.2/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
    from /home/jason/.rvm/gems/ruby-2.1.2/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
      from /home/jason/.rvm/gems/ruby-2.1.2/gems/slop-3.6.0/lib/slop.rb:211:in `parse'
      from /home/jason/.rvm/gems/ruby-2.1.2/gems/zapata-0.1.5/bin/zapata:32:in `<top (required)>'
    from /home/jason/.rvm/gems/ruby-2.1.2/bin/zapata:23:in `load'
      from /home/jason/.rvm/gems/ruby-2.1.2/bin/zapata:23:in `<main>'
      from /home/jason/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
    from /home/jason/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'

**Comment by Nedomas** [comment]
Reopen if this happens again.
