### ISSUE TITLE
raise_if_conflicts: Unable to activate rails-4.2.0

### ISSUE THREAD

**Issue by mfa213** [Nedomas/zapata#9]
got the following error while running zapata app/models/video.rb

/Users/furqan/.rbenv/versions/2.0.0-p481/lib/ruby/2.0.0/rubygems/specification.rb:2007:in `raise_if_conflicts': Unable to activate rails-4.2.0, because activesupport-3.2.14 conflicts with activesupport (= 4.2.0), activemodel-3.2.14 conflicts with activemodel (= 4.2.0), actionpack-3.2.14 conflicts with actionpack (= 4.2.0), railties-3.2.14 conflicts with railties (= 4.2.0) (Gem::LoadError)
	from /Users/furqan/.rbenv/versions/2.0.0-p481/lib/ruby/2.0.0/rubygems/specification.rb:1176:in `activate'
	from /Users/furqan/.rbenv/versions/2.0.0-p481/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:96:in `block in require'
	from /Users/furqan/.rbenv/versions/2.0.0-p481/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:95:in `each'
	from /Users/furqan/.rbenv/versions/2.0.0-p481/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:95:in `require'
	from /Users/furqan/code/greatly/config/boot.rb:4:in `<top (required)>'
	from /Users/furqan/.rbenv/versions/2.0.0-p481/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /Users/furqan/.rbenv/versions/2.0.0-p481/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /Users/furqan/code/greatly/config/application.rb:1:in `<top (required)>'
	from /Users/furqan/.rbenv/versions/2.0.0-p481/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /Users/furqan/.rbenv/versions/2.0.0-p481/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /Users/furqan/code/greatly/config/environment.rb:2:in `<top (required)>'
	from /Users/furqan/.rbenv/versions/2.0.0-p481/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /Users/furqan/.rbenv/versions/2.0.0-p481/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /Users/furqan/code/greatly/spec/rails_helper.rb:4:in `<top (required)>'
	from /Users/furqan/.rbenv/versions/2.0.0-p481/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /Users/furqan/.rbenv/versions/2.0.0-p481/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /Users/furqan/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/zapata-0.1.5/lib/zapata/core/loader.rb:38:in `load_spec_helper'
	from /Users/furqan/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/zapata-0.1.5/lib/zapata.rb:55:in `initialize'
	from /Users/furqan/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/zapata-0.1.5/lib/zapata.rb:36:in `new'
	from /Users/furqan/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/zapata-0.1.5/lib/zapata.rb:36:in `generate'
	from /Users/furqan/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/zapata-0.1.5/lib/zapata.rb:28:in `generate_with_friendly_output'
	from /Users/furqan/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/zapata-0.1.5/bin/zapata:20:in `block (3 levels) in <top (required)>'
	from /Users/furqan/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/slop-3.6.0/lib/slop.rb:260:in `call'
	from /Users/furqan/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
	from /Users/furqan/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
	from /Users/furqan/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/slop-3.6.0/lib/slop.rb:211:in `parse'
	from /Users/furqan/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/zapata-0.1.5/bin/zapata:32:in `<top (required)>'
	from /Users/furqan/.rbenv/versions/2.0.0-p481/bin/zapata:23:in `load'
	from /Users/furqan/.rbenv/versions/2.0.0-p481/bin/zapata:23:in `<main>'

**Comment by Nedomas** [comment]
Hello and thanks for raising this :heart:

I tried to recreate this on my machine with ``rails 4.2.0`` and ``rspec-rails 3.1.0``, but did not manage to get the error.

This error happens when we are trying to load your ``spec_helper`` and it in turn tries to load your app environment, which has some conflicting dependencies.

Are you using ``zapata`` from the bundle exec or globally? If it does not work with ``bundle exec``, please post your gemfile so we can recreate your environment.

Thanks!

**Comment by mfa213** [comment]
bundle exec works, thanks :)

**Comment by Nedomas** [comment]
Anytime!
